name: Docker Image Build and Push

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Push Docker image
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u nickpatton --password-stdin
        docker buildx create --name bearBuilder
        docker buildx use bearBuilder
        docker buildx inspect --bootstrap
        docker buildx build --push --tag ghcr.io/nickpatton/some-dancing-bears:$TAG --platform=linux/arm64,linux/amd64 .