name: Docker Image Build and Push

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Push Docker image
      run: |
        TAG=$(git describe --tags --abbrev=0)
        docker build . --file Dockerfile --tag ghcr.io/nickpatton/some-dancing-bears:$TAG
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u nickpatton --password-stdin
        docker push ghcr.io/nickpatton/some-dancing-bears:$TAG