name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Push Image
        run: |
          TAG=$(git describe --tags --abbrev=0)
          docker build --tag ghcr.io/nickpatton/some-dancing-bears:$TAG .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u nickpatton --password-stdin
          docker push ghcr.io/nickpatton/some-dancing-bears:$TAG
