name: Build, Scan, and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          TAG=$(git describe --tags --abbrev=0)
          docker build . --file Dockerfile --tag ghcr.io/nickpatton/some-dancing-bears:$TAG

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/nickpatton/some-dancing-bears:$TAG"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"

      - name: Push Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u nickpatton --password-stdin
          docker push ghcr.io/nickpatton/some-dancing-bears:$TAG
