name: Build, Scan, and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build and scan container image
        run: |
          TAG=$(git describe --tags --abbrev=0)
          docker build . --file Dockerfile --tag ghcr.io/nickpatton/some-dancing-bears:$TAG

          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
          trivy --version
          trivy image --format sarif -o trivy-results.sarif ghcr.io/nickpatton/some-dancing-bears:$TAG --scanners vuln
          ls -lah
          cat trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results-bad.sarif"

      # - name: Push Docker image
      #   run: |
      #     TAG=$(git describe --tags --abbrev=0)
      #     echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u nickpatton --password-stdin
      #     docker push ghcr.io/nickpatton/some-dancing-bears:$TAG
